version: "3.5"
services:

  ## Metrics Infrastructure
  
  # Prometheus
  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    volumes:
      - ./examples/multiple-services/prometheus.yaml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - example-net
  
  # Grafana
  grafana:
    container_name: grafana
    image: grafana/grafana-oss:9.0.0
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    volumes:
      - ./examples/multiple-services/grafana-provisioning:/etc/grafana/provisioning
    networks:
      - example-net
  
  loki:
    image: grafana/loki:2.6.0
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./examples/multiple-services/loki-config.yaml:/etc/loki/local-config.yaml
    networks:
      - example-net

  promtail:
    image: grafana/promtail:2.6.0
    volumes:
      - /var/log:/var/log
      - ./examples/multiple-services/promtail-config.yaml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml
    networks:
      - example-net

  # Jaeger
  jaeger-all-in-one:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger-all-in-one
    ports:
      - "16686:16686"
      - "14268"
      - "14250"
    networks:
      - example-net

  # Zipkin
  zipkin-all-in-one:
    image: openzipkin/zipkin:latest
    container_name: zipkin-all-in-one
    ports:
      - "9411:9411"
    networks:
      - example-net

  # Collector
  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.62.1
    container_name: otel-collector
    command: ["--config=/etc/otel-collector-config.yaml", "${OTELCOL_ARGS}"]
    volumes:
      - ./examples/multiple-services/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "1888:1888"   # pprof extension
      - "8888:8888"   # Prometheus metrics exposed by the collector
      - "8889:8889"   # Prometheus exporter metrics
      - "13133:13133" # health_check extension
      - "4317"        # OTLP gRPC receiver
      - "55670:55679" # zpages extension
    depends_on:
      - jaeger-all-in-one
      - zipkin-all-in-one
    networks:
      - example-net

  carbon-aware-sdk:
    image: carbon_aware:v1
    ports:
      - "80:80"
    container_name: carbon-aware-sdk
    environment:
      - CarbonAwareVars__CarbonIntensityDataSource=WattTime
      - WattTimeClient__Username=${WATTTIME_CLIENT_USERNAME:?err}
      - WattTimeClient__Password=${WATTTIME_CLIENT_PASSWORD:?err}
    networks:
      - example-net

networks:
  example-net:
    name: example-net