version: "3.5"
services:
  
  ## Application

  hello-service:
    image: hello-service:v1
    build:
      dockerfile: Dockerfile
      context: ./examples/multiple-services/hello-service
    container_name: hello-service
    ports:
      - "8082:8082"
    depends_on:
      - weather-service
    environment:
      - CARBON_AWARE_ENDPOINT=http://carbon-aware-sdk:80
      - weatherServiceForecast_baseUrl=http://weather-service:8081
    networks:
      - example-net

  weather-service:
    image: weather-service:v1
    build:
      dockerfile: Dockerfile
      context: ./examples/multiple-services/weather-service
    container_name: weather-service
    ports:
      - "8081:8081"
    environment:
      - CARBON_AWARE_ENDPOINT=http://carbon-aware-sdk:80
    networks:
      - example-net

networks:
  example-net:
    name: example-net