spring:
  application:
    name: weather-service
  carbon-aware:
    enabled: true
    endpoint: ${CARBON_AWARE_ENDPOINT}
    location: ${EMISSIONS_LOCATION:westus2}

  sleuth:
    otel:
      exporter:
        otlp:
          endpoint: http://otel-collector:4317

management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    tags:
      application: ${spring.application.name}
server:
  port: 8081
  tomcat:
    remoteip:
      port-header:

nationalWeatherService:
  baseUrl: https://api.weather.gov/