name: Build and Test

on:
  pull_request:
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        env:
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
          server-id: github
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
      - name: Build with Maven
        run: mvn -B -V package --file pom.xml
      - name: Publish snapshot package
        run: mvn -Prelease,githubRelease -B -V deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GPG_KEYNAME: ${{ secrets.GPG_KEYNAME }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
      - run: mkdir staging && cp carbon-aware-starter/target/*.jar staging
      - uses: actions/upload-artifact@v3
        with:
          name: Package
          path: staging
      - name: Update dependency graph
        uses: advanced-security/maven-dependency-submission-action@v3