name: Release a New Version

on:
  workflow_dispatch:
    inputs:
      VERSION:
        description: 'Version name that will be released'
        required: true
      DEVELOPMENT_VERSION:
        description: 'Development version name after the release'
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg-passphrase: GPG_PASSPHRASE

      - name: Install SSH Client Key
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Configure Git user
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"

      - name: Build & sign artifacts
        env:
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ./mvnw -Prelease -B -V clean install

      - name: Set up JDK 17 for OSSRH Publishing
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          server-id: ossrh
          server-username: SONATYPE_USERNAME
          server-password: SONATYPE_PASSWORD

      - name: Publish JAR to OSSRH
        env:
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
        run: |
          ./mvnw -Prelease,ossrhRelease -B -V -Dtag=v${{ github.event.inputs.version }} -DreleaseVersion=${{ github.event.inputs.version }} -DdevelopmentVersion=${{ github.event.inputs.development_version }} release:prepare release:perform

      - name: Create a GitHub Release
        run: |
          gh release create v${{ github.event.inputs.version }} --title "v${{ github.event.inputs.version }} Release"
          
          gh release upload v${{ github.event.inputs.version }} target/checkout/target/carbon-metrics-spring-boot-starter-${{ github.event.inputs.version }}.jar
          gh release upload v${{ github.event.inputs.version }} target/checkout/target/carbon-metrics-spring-boot-starter-${{ github.event.inputs.version }}-sources.jar
          gh release upload v${{ github.event.inputs.version }} target/checkout/target/carbon-metrics-spring-boot-starter-${{ github.event.inputs.version }}-javadoc.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}